name: cli_spin
description: A Dart package that enhances the user experience by displaying a sleek terminal spinner for both sync and async operations.
homepage: https://marinvitlov.com
version: 1.0.1
repository: https://github.com/mvitlov/cli_spin
issue_tracker: https://github.com/mvitlov/cli_spin/issues?q=is%3Aissue+is%3Aopen+

environment:
  sdk: ^3.0.6

dependencies:
  ansi_strip: ^0.1.1+1
  string_width: ^0.1.5
  # path: ^1.8.0

dev_dependencies:
  lints: ^2.0.0
  mocktail: ^1.0.1
  test: ^1.21.0
